name: ccn_dev_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda-version=11.8
  - cuda-runtime=12.4
  - cudatoolkit=11.8
  - jupyter=1.0.0
  - matplotlib=3.9.1
  - numpy=2.0.1
  - pandas=2.2.2
  - pip=24.2
  - python=3.12
  - pytorch=2.3.1=cuda118*
  - pytorch-cuda=12.4
  - scikit-image=0.24.0
  - scikit-learn=1.5.1
  - tifffile=2024.7.24
  - torchaudio=2.3.1
  - torchvision=0.18.1=cuda118*
  - unzip=6.0
  - zip=3.0
  - pip:
    - build==1.2.1
    - twine==5.1.1
